### ISSUE TITLE
Unable to write value

### ISSUE THREAD

**Issue by robertsLando** [Supergiovane/KNXUltimate#11]
Hi Massimo, I have created this basic program to try to toggle a group:

```ts
import { KNXClient } from 'knxultimate'
// import * as dptlib from 'knxultimate/src/dptlib'

if (process.argv.length < 3) {
	console.log('usage: %s <ga> <optional: status_ga> to toggle a light on & off',
		process.argv[1]);
	process.exit(1);
}

const groupAddress = process.argv[2]

const EVENTS = (KNXClient as any).KNXClientEvents

const client = new KNXClient({
	// ipAddr: '192.168.1.116',
	ipAddr: '224.0.23.12',
	ipPort: '3671',
	physAddr: '15.15.15',
	loglevel: 'debug',
	KNXEthInterface: 'Auto', // Bind to the first avaiable local interfavce. "Manual" if you wish to specify the interface (for example eth1); in this case, set the property interface to the interface name (interface:"eth1")
	// KNXEthInterface: "Manual", // Bind to the first avaiable local interfavce. "Manual" if you wish to specify the interface (for example eth1); in this case, set the property interface to the interface name (interface:"eth1")
	// interface: 'wlp2s0',
	suppress_ack_ldatareq: true,
	localEchoInTunneling: true, // Leave true, forever.
	hostProtocol: 'Multicast', // "Multicast" in case you use a KNX/IP Router, "TunnelUDP" in case of KNX/IP Interface, "TunnelTCP" in case of secure KNX/IP Interface (not yet implemented)
	//isSecureKNXEnabled: false, // Leave "false" until KNX-Secure has been released
	//jKNXSecureKeyring: "", // ETS Keyring JSON file (leave blank until KNX-Secure has been released)
	localIPAddress: '' // Leave blank, will be automatically filled by KNXUltimate
})

client.on(EVENTS.connected, info => {
	// The client is connected
	console.log('Connected. On Duty', info)
	onConnect()
})

function onConnect() {
	console.log('----------')
	console.log('Connected!')
	console.log('----------')

	// Now send off a couple of requests:
	console.log('\n\n\n')
	console.log('PRESS ANY KEY TO TOGGLE %s AND "q" TO QUIT.', process.argv[2])
	console.log('\n\n\n')
	let dpVal = false
	process.stdin.setRawMode(true)
	process.stdin.resume()
	process.stdin.on('data', data => {
		console.log(JSON.stringify(data))
		if (data[0] === 113) {
			if (client.isConnected()) client.Disconnect()
			process.exit(0)
		}
		dpVal = !dpVal
		console.log('Sending ' + dpVal, 'to', groupAddress)
		client.write(groupAddress, dpVal, '1.001')
	})
}

client.Connect()
```

Output:

```
api git:(knx-client) ✗ node -r esbuild-register --inspect test-knx.ts 0/0/2
Debugger listening on ws://[127.0.0.1:9229/56499022-00b6-4d32-9bdf-ce1074143ae4](https://127.0.0.1:9229/56499022-00b6-4d32-9bdf-ce1074143ae4)
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[debug] 16/4/2024, 09:14:19.49 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: lo ({"address":"[127.0.0.1](https://127.0.0.1/)","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true,"cidr":"127.0.0.1/8"})
[debug] 16/4/2024, 09:14:19.67 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: lo ({"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","internal":true,"cidr":"::1/128","scopeid":0})
[debug] 16/4/2024, 09:14:19.67 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: wlp2s0 ({"address":"[192.168.1.193](https://192.168.1.193/)","netmask":"255.255.255.0","family":"IPv4","mac":"7c:b0:c2:14:63:c4","internal":false,"cidr":"192.168.1.193/24"})
[debug] 16/4/2024, 09:14:19.67 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: wlp2s0 ({"address":"fe80::6ec2:66aa:1055:abb4","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"7c:b0:c2:14:63:c4","internal":false,"cidr":"fe80::6ec2:66aa:1055:abb4/64","scopeid":3})
[debug] 16/4/2024, 09:14:19.68 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: tun0 ({"address":"[100.100.0.14](https://100.100.0.14/)","netmask":"255.255.255.255","family":"IPv4","mac":"00:00:00:00:00:00","internal":false,"cidr":"100.100.0.14/32"})
[debug] 16/4/2024, 09:14:19.68 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: tun0 ({"address":"fe80::114b:d34:5180:beb3","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"00:00:00:00:00:00","internal":false,"cidr":"fe80::114b:d34:5180:beb3/64","scopeid":4})
[debug] 16/4/2024, 09:14:19.68 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: tun1 ({"address":"[10.9.1.61](https://10.9.1.61/)","netmask":"255.255.255.255","family":"IPv4","mac":"00:00:00:00:00:00","internal":false,"cidr":"10.9.1.61/32"})
[debug] 16/4/2024, 09:14:19.68 KNXUltimate-KNXEngine: ipAddressHelper.js: parsing interface: tun1 ({"address":"fe80::d27e:fd6e:c7df:f19c","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"00:00:00:00:00:00","internal":false,"cidr":"fe80::d27e:fd6e:c7df:f19c/64","scopeid":5})
Connected. On Duty {
 ipAddr: '[224.0.23.12](https://224.0.23.12/)',
 ipPort: '3671',
 physAddr: KNXAddress { type: 0, level: 3, _address: 65295, length: 2 },
 loglevel: 'debug',
 KNXEthInterface: 'Auto',
 suppress_ack_ldatareq: true,
 localEchoInTunneling: true,
 hostProtocol: 'Multicast',
 localIPAddress: '[192.168.1.193](https://192.168.1.193/)',
 connectionKeepAliveTimeout: 30,
 localSocketAddress: undefined
}
----------
Connected!
----------




PRESS ANY KEY TO TOGGLE 0/0/2 AND "q" TO QUIT.




{"type":"Buffer","data":[49]}
Sending true to 0/0/2
[debug] 16/4/2024, 09:14:19.675 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.15 dstAddress: 0/0/2 Host:[224.0.23.12:3671](https://224.0.23.12:3671/) channelID:undefined seqCounter:undefined Dest:0/0/2 Data:01 TPCI:Write
[debug] 16/4/2024, 09:14:19.680 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.15 dstAddress: 0/0/2 Host:[224.0.23.12:3671](https://224.0.23.12:3671/)
{"type":"Buffer","data":[48]}
Sending false to 0/0/2
[debug] 16/4/2024, 09:14:20.534 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.15 dstAddress: 0/0/2 Host:[224.0.23.12:3671](https://224.0.23.12:3671/) channelID:undefined seqCounter:undefined Dest:0/0/2 Data:00 TPCI:Write
[debug] 16/4/2024, 09:14:20.535 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.15 dstAddress: 0/0/2 Host:[224.0.23.12:3671](https://224.0.23.12:3671/)
{"type":"Buffer","data":[49]}
Sending true to 0/0/2
[debug] 16/4/2024, 09:14:21.215 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.15 dstAddress: 0/0/2 Host:[224.0.23.12:3671](https://224.0.23.12:3671/) channelID:undefined seqCounter:undefined Dest:0/0/2 Data:01 TPCI:Write
[debug] 16/4/2024, 09:14:21.216 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.15 dstAddress: 0/0/2 Host:[224.0.23.12:3671](https://224.0.23.12:3671/)
{"type":"Buffer","data":[113]}
Waiting for the debugger to disconnect...
/home/daniel/GitProjects/mqtt-gateway/node_modules/knxultimate/src/KNXClient.js:649
 throw new Error('KNX Socket is already disconnected')
 ^

Error: KNX Socket is already disconnected
 at KNXClient.Disconnect (/home/daniel/GitProjects/mqtt-gateway/node_modules/knxultimate/src/KNXClient.js:649:13)
 at ReadStream.<anonymous> (/home/daniel/GitProjects/mqtt-gateway/packages/api/test-knx.ts:52:37)
 at ReadStream.emit (node:events:514:28)
 at addChunk (node:internal/streams/readable:376:12)
 at readableAddChunk (node:internal/streams/readable:349:9)
 at Readable.push (node:internal/streams/readable:286:10)
 at TTY.onStreamRead (node:internal/stream_base_commons:190:23)
```

Two things I noticed also:
- Disconnect() always throws (see error above)
- There should be some defgault values in options, If for example I don't specify the ipPort in options it connects but then fails to send packets: `[error] 16/4/2024, 09:15:33.515 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Port should be > 0 and < 65536. Received undefined. object seqCounter:undefined`

**Comment by Supergiovane** [comment]
Ciao Daniel
Sei sicuro che il tuo router KNX, non filtri i telegrammi provenienti da un indirizzo fisico diverso dal suo? Stai usando "physAddr: '15.15.15'," mentre vedo che il tuo router è sulla linea 10.15.1.
Entra dentro le proprietà del router KNX e cerca le tabelle di filtro. Di solito, se imposti "inoltra tutto" (o, certe volte, trovi anche il checkbox "debug", che fa la stessa cosa), il router inizia a trasferire i telegrammi correttamente.

**Comment by Supergiovane** [comment]
Per l'errore Error('KNX Socket is already disconnected'), non dovrebbe throwwarlo se il client non è già disconnesso. Poi ci do un occhio.

**Comment by robertsLando** [comment]
> Sei sicuro che il tuo router KNX, non filtri i telegrammi provenienti da un indirizzo fisico diverso dal suo? Stai usando "physAddr: '15.15.15'," mentre vedo che il tuo router è sulla linea 10.15.1.

Ho provato anche a mettere 10.15.1 come indirizzo fisico e il risultato è lo stesso

**Comment by Supergiovane** [comment]
> > Sei sicuro che il tuo router KNX, non filtri i telegrammi provenienti da un indirizzo fisico diverso dal suo? Stai usando "physAddr: '15.15.15'," mentre vedo che il tuo router è sulla linea 10.15.1.
> 
> Ho provato anche a mettere 10.15.1 come indirizzo fisico e il risultato è lo stesso

Non possono coesistere due dispositivi con lo stesso indirizzo fisico. :-) Al limite, imposta 10.15.50, così eviti di scontrarti anche con i ragnetti KNX.

**Comment by Supergiovane** [comment]
Ah, ma questo non è un router, è un'interfaccia.
Usa questo codice:

```javascript

const client = new KNXClient({
	ipAddr: '192.168.1.116', // QUI METTI L'INDIRIZZO IP DELL'INTERFACCIA
	ipPort: '3671',
	physAddr: '15.15.15',
	loglevel: 'debug',
	KNXEthInterface: 'Auto', // Bind to the first avaiable local interfavce. "Manual" if you wish to specify the interface (for example eth1); in this case, set the property interface to the interface name (interface:"eth1")
	// KNXEthInterface: "Manual", // Bind to the first avaiable local interfavce. "Manual" if you wish to specify the interface (for example eth1); in this case, set the property interface to the interface name (interface:"eth1")
	// interface: 'wlp2s0',
	suppress_ack_ldatareq: true,
	localEchoInTunneling: true, // Leave true, forever.
	hostProtocol: 'TunnelUDP', // QUI METTI TunnelUDP PERCHE' SI TRATTA DI UN'INTERFACCIA KNX/IP
	localIPAddress: '' // Leave blank, will be automatically filled by KNXUltimate
})
```

Un'interfaccia KNX/IP risponde solo tramite protocollo UDP unicast in tunnel (TunnelUDP), mentre un router fa sia l'unicast sul suo IP,  che il multicast sull'IP multicast 224.0.23.12

**Comment by robertsLando** [comment]
Oooooh finally! Grazie mille Massimo ora funziona! 🎉  

In questo caso la disconnect non lancia più errore, però penso non dovesse lanciarlo nemmeno prima dal momento che l'evento 'connected' era stato lanciato e isConneted tornava true.

Dopo vari connect/disconnect ora non mi si connette più e vedo questo errore:

```
[error] 16/4/2024, 11:56:09.532 KNXUltimate-KNXEngine: Received KNX packet: Error processing inbound message: The value of "offset" is out of range. It must be >= 0 and <= 10. Received 12 Data received: 06100206001200240801c0a801740e570204 srcAddress: {"address":"192.168.1.116","family":"IPv4","port":3671,"size":18} ChannelID:null Host:192.168.1.116:3671. This means that KNX-Ultimate received a malformed Header or CEMI message from your KNX Gateway.
```

**Comment by robertsLando** [comment]
Ora è tornato a funzionare dal nulla, boh 🤷🏼‍♂️  Oggi pome se riesco inizio a buttarti giù il refactor in ts!

**Comment by Supergiovane** [comment]
Potrebbe essere che l'interfaccia abbia finito i tunnel disponibili. Sì, perchè le interfacce KNX/IP hanno un numero di tunnels prestabilito, per esempio e o 4.
Se aspetti un po', i tunnels vengono liberati automaticamente.
